# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6df2b372d86394e601911d85c73971a3eb9fa41deea383707f194cf83241b256ee6f2620daaf644f82a236eb3da1069e990b146f0f175995cdb72f2c4ff0aaf1

test:
  secret_key_base: 81b2c0842bdd4baf46b5733152cc577b0de5f40ea63b53a7256c27306f1da6f793574376d7cc237e9ace07281aeb36c93168707de382b9978f3332876bd31c9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
